server:
  port: 9081
  tomcat:
    basedir: temp # 设置临时文件
spring:
  application:
    name: file-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.57.2:3306/dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Root@529
  jackson:
    time-zone: GMT+8
    joda-date-time-format: yyyy-MM-dd HH:mm
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    #    redis数据库地址
    host: 47.101.57.2     #这里填你的阿里云地址
    port: 3200
    password: kevin

# 自定义日志文件路径配置
logging:
  config: classpath:logback/logback-spring-dev.xml
  path: logs/file-service/

eureka:
  client:
    service-url:
      defaultZone: http://47.101.57.2:8000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}



fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 60
    height: 60
  tracker-list:
    - 47.101.57.2:22122
  web-server-url: 47.101.57.2:90

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  #  typeAliasesPackage: com.yourpackage.*.entity
  global-config:
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    #    id-type: 3
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    # Sequence序列接口实现类配置
    #    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    db-config:
      #      用户输入ID,该类型可以通过自己注册自动填充插件进行填充
      id-type: input
  #    logic-delete-value: 1
  #    logic-not-delete-value: 0
  #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  #    #自定义填充策略接口实现
  #    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

snowflakeldWorker:
  workerId: 0
  datacenterId: 0

